server:
  url: https://tu-delft-heritage.github.io/watertijdreis-data

# Run these everywhere.
run:
  - folder-collections
  - flat-manifests
  # - extract-remote-source
  # - extract-slug-source
  # - extract-part-of-collection
  # - extract-thumbnail-local
  - manifest-sqlite
  # - metadata-analysis
  # - site-collections

collections:
  index:
    label: { "en": "Waterstaatskaart", "nl": "Waterstaatskaart" }

stores:
  waterstaatskaart:
    type: iiif-json
    path: ./content/iiif-manifests
    destination: manifests
    pattern: "**/*.{json,yaml,yml}"
